apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webApp-deploy
  labels:
    app: java-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-web-app
  template:
    metadata:
      labels:
        app: java-web-app
    spec:
      containers:
      - name: java-webApp-container
        image: junaidm3699/java-web-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-webApp-np-service
  labels:
    app: java-web-app
spec:
  selector:
    app: java-web-app

  type: NodePort
  ports:
  - nodePort: 31002
    port: 8080
    targetPort: 8080
